### ISSUE TITLE
Payment Retry Issue with Outstanding Balance Using AutoAleet API

### ISSUE THREAD

**Issue by uridedavid** [Autofleet/locomotion#860]
There is an issue where the AutoAleet API rejects payment retries for the outstanding balance. This occurs both on the mobile app and the web's control page. It is suspected that the issue might be related to test credit card usage or another underlying API behavior.

Steps to Reproduce:
Navigate to the payment section with an outstanding balance.
Attempt to retry payment using the api/v1/me/customers/:paymentId/retry API endpoint.
Observe the rejection error.

Environment:
Platform: Mobile App & Web Control Page
API Involved: AutoAleet API (api/v1/me/customers/:paymentId/retry)
Relevant Logs: (Refer to the attached video and screenshots for detailed logs and reproduction steps)

Attachments:
Video showcasing the issue: <img width="642" alt="Screenshot 2024-12-10 at 14 39 26" src="https://github.com/user-attachments/assets/bf2c4676-88fa-4927-9f1f-3e6979d746b9">
Relevant Ride Details: Link to the web ride details
Credit card using: 4242 with Stripe card test

Additional Notes:
This issue is blocking successful payment retries and affects multiple users across platforms. Assistance is required to resolve this as soon as possible.

**Comment by OmerGery** [comment]
Hey, 
Please send the trace id here as a comment

**Comment by uridedavid** [comment]
@OmerGery 
This guy:
- traceId: 9dtYhpQqK
- The response returned successfully but only got the reject status.
`{
    "id": "50dd74d0-9018-44bc-9bca-75c2bab074bd",
    "paymentAccountId": "89069332-a1b1-46c5-ae35-a3fe990e9aea",
    "customerId": "e0455191-6d2e-49d9-a7e9-422a08db46bf",
    "paymentMethodId": "34fc861c-163e-46de-8a87-3e16dec8ebe4",
    "state": "rejected",
    "stripeIntentId": "pi_3QRt4gL0Z6nKgMqT0Rfgos4m",
    "priceCalculationId": "58553adb-6f19-411a-ad23-da525d6587f9",
    "rideId": "47faf2e9-1a48-4ed1-8ab0-b6e044922fc7",
    "currency": "CAD",
    "driverId": null,
    "createdAt": "2024-12-03T10:11:22.823Z",
    "updatedAt": "2024-12-05T06:49:59.250Z",
    "deletedAt": null
}`

<img width="1506" alt="Screenshot 2024-12-18 at 09 47 49" src="https://github.com/user-attachments/assets/8335f77b-a65a-497c-98af-03ea69ec931b" />
<img width="1507" alt="Screenshot 2024-12-18 at 09 48 01" src="https://github.com/user-attachments/assets/72de9103-06ba-485a-a849-976bb4f748d7" />

**Comment by Porat34** [comment]
We have identified this issue is a clone of a similar bug we are already handling, we will update here once its resolved

**Comment by uridedavid** [comment]
Any update? @Porat34

**Comment by AlonAF800** [comment]
The ride was corrected.
let us know if it happens again

**Comment by joseuride** [comment]
This issue has not been fixed yet, and I still encounter this error when trying to retry on the web.
@AlonAF800 please check again with x-trace-id:etBmaIAcX

![Image](https://github.com/user-attachments/assets/555db81c-7435-4562-a41d-e9d2b1b68df8)

![Image](https://github.com/user-attachments/assets/a33333e9-39cc-488e-bbb1-f053e706d32a)

**Comment by Porat34** [comment]
Hi Jose,
Those rides are very old and have been settled.
You may try this with a new ride and it should be fine.
If you keep running into issues please approach our team through Slack or the email inbox as Git is reserved for development efforts of the rider app only. Thank you
